### ISSUE TITLE
Functions not highlighted

### ISSUE THREAD

**Issue by peitl** [vale1410/vim-minizinc#4]
Functions such as `sum` or `product` are not highlighted in MiniZinc files. I see such functions are listed for the other file formats, but not for MiniZinc. Is it because this is based on an older MiniZinc standard, or am I doing something wrong? Would be a good idea to add, I can maybe open a pull request. Thanks.

**Comment by vale1410** [comment]
Hi Tomáš, 
I haven't updated the minizinc syntax file in years - happy to do so if you can provide me the update. Thanks in advance !
